spring.application.name=AccountService
spring.datasource.url = jdbc:mysql://root:IjuzGlFnHQZVGQnLKsdyUFhsaKEUbSRz@shortline.proxy.rlwy.net:41677/PortAccount
spring.datasource.username = root
spring.datasource.password = IjuzGlFnHQZVGQnLKsdyUFhsaKEUAbSRz